### ISSUE TITLE
Regras botões tarefas

### ISSUE THREAD

**Issue by joshuapassos** [RecodeJr/Gamification#22]

**Comment by ednailson** [comment]
# Botões de Minhas Tarefas
**Editar**: Só pode editar a tarefa o criador da tarefa e se o status da tarefa for "Disponivel"
**Cancelar**: Só pode cancelar a tarefa o criador da tarefa.
**Finalizar**: Só pode finalizar a tarefa quem pegou a tarefa.

# Botão de Disponiveis
**Leia mais**: Exibe todas as informações da tarefa.
**Pegar**: Botão pegar está no "modal" que é aberto ao clicar no Leia mais
